// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABH3yrUm_o-nC91QDBT7KIvLSoG12tEik',
    appId: '1:944999712763:web:5ee96cc9db138122d8ad5e',
    messagingSenderId: '944999712763',
    projectId: 'cartracking-af307',
    authDomain: 'cartracking-af307.firebaseapp.com',
    databaseURL: 'https://cartracking-af307-default-rtdb.firebaseio.com',
    storageBucket: 'cartracking-af307.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm_pn4dwzHM8nMr8aQbgvhOTpwmoixtRw',
    appId: '1:944999712763:android:66563e0c4dca1496d8ad5e',
    messagingSenderId: '944999712763',
    projectId: 'cartracking-af307',
    databaseURL: 'https://cartracking-af307-default-rtdb.firebaseio.com',
    storageBucket: 'cartracking-af307.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKn3cFVLifx5hoRq5f5drWXCfMzTMIhew',
    appId: '1:944999712763:ios:ed00411bfc109ce4d8ad5e',
    messagingSenderId: '944999712763',
    projectId: 'cartracking-af307',
    databaseURL: 'https://cartracking-af307-default-rtdb.firebaseio.com',
    storageBucket: 'cartracking-af307.appspot.com',
    iosBundleId: 'com.example.carTracking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKn3cFVLifx5hoRq5f5drWXCfMzTMIhew',
    appId: '1:944999712763:ios:869bd521347a961dd8ad5e',
    messagingSenderId: '944999712763',
    projectId: 'cartracking-af307',
    databaseURL: 'https://cartracking-af307-default-rtdb.firebaseio.com',
    storageBucket: 'cartracking-af307.appspot.com',
    iosBundleId: 'com.example.carTracking.RunnerTests',
  );
}
